### ISSUE TITLE
Uncaught ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by dsandstrom** [bradleyboy/tidy-tabs-atom#2]
I'm getting an error after updating to Atom 0.199 on OSX.  It seems Atom doesn't include the fs module anymore.  PR on it's way.

**Comment by JamieREvans** [comment]
I'm still having this issue

**Comment by dsandstrom** [comment]
It was merged, but a new version hasn't been published to Atom.  You could
download and `apm link` until it is.

**Comment by bradleyboy** [comment]
Oops, sorry. I forgot to push this. Will take care of that today.

**Comment by bradleyboy** [comment]
Pushed now as part of 0.1.2.

**Comment by JamieREvans** [comment]
Awesome!

Although, for some reason, Atom thinks you have released v0.1.3, but it fails to update with a 404 (since you're actually at 0.1.2)

**Comment by bradleyboy** [comment]
Ugh, not sure how I flubbed this up with apm. Republished as 0.2.0, let me know if that works better.
