### ISSUE TITLE
[SUGGESTION] Tabs limit to keep open

### ISSUE THREAD

**Issue by shadoWalker89** [bradleyboy/tidy-tabs-atom#9]
Hi,
First of all i want to thank you for the great package.
When i use it i end up with a little number of tabs.

Is it possible to add a "tab_threshold" setting that will keep N tabs open ignoring the "accessed threshold" and the "modified threshold"

This way we will never end up with 3 or 4 tabs open but have the value of the setting "tab_threshold" open. (it could have a default setting of 10)

If the "tab_threshold" value is 0 it means that the user wants to disable this feature

**Comment by bradleyboy** [comment]
@shadoWalker89 There's actually already a setting for this :)

Look for the "Minimum number of tabs" setting. When you have this set, the plugin will only start closing tabs when you have more than that threshold.

**Comment by shadoWalker89** [comment]
I'm afraid that the "Minimum number of tabs" setting will not do it, and this is the explanation

Imagine that we have "Minimum number of tabs" setting = 4

I have 25 tabs open.
When i execute the command we do have more then 4 tabs open, so the package will close the tabs depending on the modified and accessed thresholds, for example the package will close 20 tabs and we will remain with only 5 tabs opened.

If we add the "tab_threshold" and set it to 10, assuming that the package is going to close 20 tabs depending on modified and accessed thresholds. But because we have the "tab_threshold" setting, it must leave no matter what 10 tabs open. 
So instead the package will close only 15 tabs and leave 10 open.

The logic is we close the tabs that meet the modified and accessed thresholds and order them by priority (close the oldest tabs) as long we keep the number of tabs in the setting "tab_threshold" opened.
